cryptopan-key = ### EDIT Set a good secret and put it here, e.g. "somesecret"
input-tcp = ### EDIT Set "ip:port" where EDM should listen for DNSTAP packets, e.g. "127.0.0.1:53535"
mqtt-signing-key-file = "{{.SignkeyPath}}"
mqtt-client-cert-file = "{{.ClientCertPath}}"
mqtt-client-key-file = "{{.ClientKeyPath}}"
http-signing-key-file = "{{.SignkeyPath}}"
http-client-cert-file = "{{.ClientCertPath}}"
http-client-key-file = "{{.ClientKeyPath}}"
mqtt-ca-file = "{{.CaCertPath}}"
mqtt-server = "{{.MqttBroker}}"
http-url = "{{.AggrecUrl}}"
ignored-client-ips-file = "/etc/dnstapir/edm/ignored-ips"
ignored-question-names-file = "/etc/dnstapir/edm/ignored.dawg"
disable-mqtt-filequeue = true
minimiser-workers = 4
disable-session-files = true
well-known-domains-file = "/etc/dnstapir/edm/well-known-domains.dawg"
