cryptopan-key = ### EDIT Choose a good secret and put it here
input-tcp = ### EDIT add ip+port of resolver's DNSTAP interface here
mqtt-signing-key-file = "{{.SignkeyPath}}"
mqtt-client-cert-file = "{{.ClientCertPath}}"
mqtt-client-key-file = "{{.ClientKeyPath}}"
http-signing-key-file = "{{.SignkeyPath}}"
http-client-cert-file = "{{.ClientCertPath}}"
http-client-key-file = "{{.ClientKeyPath}}"
mqtt-ca-file = "{{.CaCertPath}}"
mqtt-server = "{{.MqttBroker}}"
http-url = "{{.AggrecUrl}}"
ignored-client-ips-file = "/etc/dnstapir/edm/ignored-ips"
ignored-question-names-file = "/etc/dnstapir/edm/ignored.dawg"
debug-enable-blockprofiling = false
debug-enable-mutexprofiling = false
disable-mqtt-filequeue = true
minimiser-workers = 4
disable-session-files = true
well-known-domains-file = "/etc/dnstapir/edm/well-known-domains.dawg"
